apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  paths: |-
    {{- range $group, $paths := .Values.paths }}
    {{- range $paths }}
    - name: {{ .name }}
      path: {{ .path }}
      claim: {{ default .name .claim }}
    {{- end }}
    {{- end }}
